name: 'Publish package'
on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

permissions:
    contents: read
jobs:
    release:
        runs-on: ubuntu-latest
        permissions:
            contents: write
            issues: write
            pull-requests: write
            id-token: write
            packages: write
        steps:
            - name: Checkout
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0
            - name: Setup Node
              uses: actions/setup-node@v4
              with:
                  node-version: latest
                  registry-url: 'https://npm.pkg.github.com'
                  scope: '@aabeborn'
            - name: Add Bun
              uses: oven-sh/setup-bun@v1
              with:
                  registry-url: 'https://npm.pkg.github.com'
                  scope: '@aabeborn'
            - name: Install dependencies
              env:
                  BUN_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
              run: bun install --frozen-lockfile
            - name: Publish package
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  NPM_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
              run: bunx semantic-release
